spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangjunyong8888888/springcloud-config.git
          username: m17600401239@163.com
          password: Zhang.521
          #basedir: D:\soft\IDEA-work\SpringCloud\config\basedir
  rabbitmq:
    addresses: 192.144.204.158
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7080
management:
  endpoints:
    web:
      exposure:
        include: "*"